### PR TITLE
Code fix and more organized structure

### PR DESCRIPTION
**Pull request by ppamorim**
Some items was changed:
 - Unnecessary libraries removed
 - More correct build.gradle file
 - Lower API
 - ProgressLayout now extends View, RelativeLayout is unnecessary in this case
 - Resources cleanup
 - Licenses added

Can you merge?

### CODE REVIEW

**Comment by ppamorim** [comment]
@iammert Would ProgressLayout extends Drawable? Now I simple extends View. But extending Drawable can show some performance tips, look like this sample:

https://github.com/rey5137/material/blob/master/lib/src/main/java/com/rey/material/drawable/CircularProgressDrawable.java

**Comment by ppamorim** [comment]
If you merge this, I can solve #2 too. :)

**Comment by ppamorim** [comment]
We would change the source code style to square java style. What do you think about it?

**Comment by iammert** [comment]
Thanks for PR! That makes me happy that you are interested about lib. I would like to learn something about your new PRs . So go for it :)

**Pull request merged**
